### ISSUE TITLE
quiptools-cuda not installing properly from requirements 

### ISSUE THREAD

**Issue by tdolan21** [cognitivecomputations/laserRMT#1]
ERROR: Could not find a version that satisfies the requirement quiptools-cuda==0.0.0 (from versions: none)
ERROR: No matching distribution found for quiptools-cuda==0.0.0

I tried removing the version restriction but that did not help either.

ERROR: Could not find a version that satisfies the requirement quiptools-cuda (from versions: none)
ERROR: No matching distribution found for quiptools-cuda

**Comment by fernando-neto-ai** [comment]
Sorry. It seems my requirements was contaminated. Try removing it and go on, since it won't be used
